# Generated by Django 6.0.6 on 2026-07-07 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ssn_last4', models.CharField(blank=True, max_length=4, verbose_name='SSN (last 4 digits)')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'High Yield Savings'), ('both', 'Checking + Savings')], default='checking', max_length=10)),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_question', models.CharField(blank=True, max_length=255)),
                ('security_answer', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
