# Generated by Django 6.0.6 on 2026-07-07 09:46

import bank.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Primary Checking'), ('savings', 'Savings Account')], max_length=10)),
                ('account_number', models.CharField(default=bank.models._generate_account_number, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_type'],
                'unique_together': {('user', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('internal', 'Internal Transfer'), ('external', 'External Transfer')], max_length=10)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_account_number', models.CharField(blank=True, max_length=34)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Successful'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('balance_applied', models.BooleanField(default=False, help_text="Internal flag — set once funds have actually moved, so flipping status back and forth in admin can't double-apply.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='bank.account')),
                ('to_account', models.ForeignKey(blank=True, help_text="Only set for internal transfers between the user's own accounts.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='bank.account')),
                ('user', models.ForeignKey(help_text='The account holder who initiated this transfer.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
