# Generated by Django 6.0.6 on 2026-07-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_profile_biometric_enabled_profile_notify_low_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_applied',
            field=models.BooleanField(default=False, help_text='Internal flag — set once the destination account has been credited (internal transfers only), which happens when the transaction is marked completed.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded',
            field=models.BooleanField(default=False, help_text='Internal flag — set if a held transfer was later marked failed and the funds were returned to the source account.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_applied',
            field=models.BooleanField(default=False, help_text="Internal flag — set once the transfer amount has been held (debited from the source account). This happens immediately when the transfer is submitted, not when it's marked completed."),
        ),
    ]
